### ISSUE TITLE
Update dependency on snapdragon-node to the latest (v2.1.1)

### ISSUE THREAD

**Issue by rbecheras** [here-be/snapdragon#21]
cf. https://github.com/here-be/snapdragon/issues/20#issuecomment-393243321

**Comment by jonschlinkert** [comment]
No, instead you can just do:

**Comment by rbecheras** [comment]
Yes, it what I do for now. But I'm asking, why do you consider that we shouldn't update the `snapdragon-node` dependency to the latest in the `snapdragon` main module ?

**Comment by rbecheras** [comment]
In fact no, we can't do that because `Parser` use `pushNode()` internally in `init()`, called by `parse()`


```js
home/remi/app/node_modules/snapdragon/lib/parser.js:76
    this.ast.pushNode(this.bos);
             ^

TypeError: this.ast.pushNode is not a function
    at Parser.init (/home/remi/app/node_modules/snapdragon/lib/parser.js:76:14)
    at Parser.parse (/home/remi/app/node_modules/snapdragon/lib/parser.js:524:10)
    at Object.<anonymous> (/home/remi/app/src/lib/index.js:15:20)
    at Module._compile (module.js:652:30)
    at loader (/home/remi/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/remi/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

So I'll use `pushNode()` for now. It's not a problem.

**Comment by jonschlinkert** [comment]
> Yes, it what I do for now. But I'm asking, why do you consider that we shouldn't update the snapdragon-node dependency to the latest in the snapdragon main module ?

I've mentioned in a few places that I'm actively working on the next version of snapdragon and other libs. I would much rather spend the time getting closer to that goal than handling issues related to unforeseen problems caused by bumping a dep.

**Comment by rbecheras** [comment]
Ok Jon thank you very much for your explanations.
If you need help with snapdragon I'll be pleased to help!

Here is again an awesome lib to build awesome tools!
